### ISSUE TITLE
Error with package "outlines"

### ISSUE THREAD

**Issue by zzjchen** [thu-wyz/inference_scaling#4]
I cloned your repo, and tried to install the dependencies according to your instruction. But when I run `bash scripts/run_reward.sh` or `bash scripts/run_policy.sh`, I got the following error for package outlines (version 0.1.4).
``` python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/storage/home/user/codes/inf_scale/inference_scaling/sglang/python/sglang/launch_server.py", line 3, in <module>
    from sglang.srt.server import ServerArgs, launch_server
  File "/storage/home/user/codes/inf_scale/inference_scaling/sglang/python/sglang/srt/server.py", line 26, in <module>
    from sglang.srt.constrained import disable_cache
  File "/storage/home/user/codes/inf_scale/inference_scaling/sglang/python/sglang/srt/constrained/__init__.py", line 6, in <module>
    from outlines.fsm.fsm import RegexFSM
ModuleNotFoundError: No module named 'outlines.fsm.fsm'
```
This cannot be resolved even if I try to reinstall outlines with `pip install --force-reinstall outlines`. I found that the "outlines" package is a dependency for sglang. In your forked sglang repo  https://github.com/thu-wyz/sglang/blob/9e9974d49e64739b5210b1195aa64305ec8687d1/python/pyproject.toml#L23 , "outlines" should be higher than 0.0.27. But I thought perhaps it should be also lower than 0.1.0? 
Can you share your version of the outlines package, so that I can make things right easily?

**Comment by thu-wyz** [comment]
Yes, 0.0.44 works for me.

**Comment by zzjchen** [comment]
Thanks, I'll try it out

**Comment by zzjchen** [comment]
It works for me! Thanks a lot
