### ISSUE TITLE
Question about REBASE (and probably related to reward model)

### ISSUE THREAD

**Issue by zzjchen** [thu-wyz/inference_scaling#6]
I tried to run rebase.sh according to your instruction on an A100 machine, but always gets the following error, after a very fast progress bar finished. Is there anything wrong? 
``` python
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 498/500 [00:07<00:00, 68.94it/s]Traceback (most recent call last):
  File "/storage/home/lanzhenzhongLab/chenzijie/codes/inf_scale/inference_scaling/rebase.py", line 292, in <module>
    main(args)
  File "/storage/home/lanzhenzhongLab/chenzijie/codes/inf_scale/inference_scaling/rebase.py", line 270, in main
    states = reward_guided_search.run_batch(input_list_dict, backend=RuntimeEndpoint(args.policy_host), num_threads=paras["num_threads"], progress_bar=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/lanzhenzhongLab/chenzijie/anaconda3/envs/inf_scale/lib/python3.11/site-packages/sglang/lang/ir.py", line 250, in run_batch
    return run_program_batch(
           ^^^^^^^^^^^^^^^^^^
  File "/storage/home/lanzhenzhongLab/chenzijie/anaconda3/envs/inf_scale/lib/python3.11/site-packages/sglang/lang/interpreter.py", line 153, in run_program_batch
    rets = [f.result() for f in futures]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/lanzhenzhongLab/chenzijie/anaconda3/envs/inf_scale/lib/python3.11/site-packages/sglang/lang/interpreter.py", line 153, in <listcomp>
    rets = [f.result() for f in futures]
            ^^^^^^^^^^
  File "/storage/home/lanzhenzhongLab/chenzijie/anaconda3/envs/inf_scale/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/storage/home/lanzhenzhongLab/chenzijie/anaconda3/envs/inf_scale/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/storage/home/lanzhenzhongLab/chenzijie/anaconda3/envs/inf_scale/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/lanzhenzhongLab/chenzijie/anaconda3/envs/inf_scale/lib/python3.11/site-packages/sglang/lang/interpreter.py", line 79, in run_program
    run_internal(state, program, func_args, func_kwargs, sync)
  File "/storage/home/lanzhenzhongLab/chenzijie/anaconda3/envs/inf_scale/lib/python3.11/site-packages/sglang/lang/interpreter.py", line 44, in run_internal
    raise e
  File "/storage/home/lanzhenzhongLab/chenzijie/anaconda3/envs/inf_scale/lib/python3.11/site-packages/sglang/lang/interpreter.py", line 42, in run_internal
    state.ret_value = program.func(state, *func_args, **func_kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/lanzhenzhongLab/chenzijie/codes/inf_scale/inference_scaling/rebase.py", line 198, in reward_guided_search
    continue_search = tree.select_and_expand(depth)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/lanzhenzhongLab/chenzijie/codes/inf_scale/inference_scaling/rebase.py", line 187, in select_and_expand
    self.expand(expand_node, width)
  File "/storage/home/lanzhenzhongLab/chenzijie/codes/inf_scale/inference_scaling/rebase.py", line 104, in expand
    fork.set_score_backend(self.reward_backend)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ProgramState' object has no attribute 'set_score_backend'
```

**Comment by zzjchen** [comment]
The policy model seems to work well from the log (with 500 generate request processed successfully). But the reward models log contains 500 requests of 

```INFO:     127.0.0.1:42488 - "GET /get_model_info HTTP/1.1" 200 OK```

Since I'm testing on MATH500, I guess it is doing one step for each test data? 

Is anything wrong here?

**Comment by thu-wyz** [comment]
Please check whether you have installed the correct version. The sglang version should be 0.0.14. You can use pip install . in sglang/python

**Comment by zzjchen** [comment]
It's hard for me to figure out how requests to the reward model are posted. For example
I have the reward model (same as your paper) deployed, and its URL is ```http://127.0.0.1:30010```. And I have a question and answer that looks like:
```  
"How many positive whole-number divisors does 196 have?Step 1: The prime factorization of 196 is $2^2 \\cdot 7^2$. \u043a\u0438\nStep 2: To find the number of divisors, we consider the exponents of the prime factors. \u043a\u0438\nStep 3: For each prime factor, we have 3 choices: include 0, include 1, or include 2. \u043a\u0438\nStep 4: Therefore, the number of positive whole-number divisors is $(2+1)(2+1)=\\boxed{9}$.The answer is: 9 \u043a\u0438"
``` 
Could you show me how to post an HTTP request such that I can get the score of this data sample? It's better if you can use things like ```requests``` library or the ```curl``` shell command.

**Comment by thu-wyz** [comment]
Requests are made by:
state += text (text needs to be rewarded)
state += gen("score", max_tokens=0, forward_only=True, logits_require_id=8094)
Then state.scores() will give you a list of scores.
last_score = state.scores()[-1]
You can refer to SGlang document what are "state" and function "gen".
